SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    COMMENTS
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = LOWER(?) AND TABLE_NAME = 'Books'
ORDER BY ORDINAL_POSITION;